services:
  fastapi:
    working_dir: /app
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo-db
    ports:
      - "${EXTERNAL_FASTAPI_PORT}:${INTERNAL_FASTAPI_PORT}"
    command: ["fastapi", "run", "./src/main.py", "--port", "${INTERNAL_FASTAPI_PORT}"]

  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
