services:
  fastapi:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    ports:
      - "80:8000"
    env_file:
      - .env
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
