services:
  payment-service:
    working_dir: /app
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: payment_app
    restart: always
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - mongodb-service

  mongodb-service:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB__USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB__PASSWORD}

volumes:
  mongo_data:
